services:
  - docker

matrix:
  include:
    - language: go

      go:
        - 1.12.x

      env:
        - GO111MODULE=on

      script:
        - make lint-prepare
        - make lint
        - make test

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: python

      python:
        - "3.6"

      script:
        - cd test/e2e
        - make e2e-test
